export const ALL_QUESTION_LOADING = "ALL_QUESTION_LOADING";
export const ALL_QUESTION_SUCCESS = "ALL_QUESTION_SUCCESS";
export const ALL_QUESTION_FAIL = "ALL_QUESTION_FAIL";


export const CLEAR_ERROR= "CLAER_ERROR";